* Config.org: A configuration file for Emacs.
** [TODO] Introduction.
I do like to fiddle around with Emacs. But the infinitely extensible
editor invites the process of fiddling around.

** [TODO] Suggested Structure for config.org.
*** Set up the MELPA Repository.

**** [TODO] Information about packages, including installing and updating.

#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/"))
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
#+end_src

#+begin_src emacs-lisp
  (require 'use-package)
#+end_src


*** Look and Feel Customisation.
**** Look and Feel 'Built In' Customisation.
Entries in this section modify the look and feel of Emacs using just
those configuration options which are available by default with
Emacs.  Most of these are about increasing the available real-estate
for my Emacs page and turning off unnecessary splash screens etc.

#+begin_src emacs-lisp
  (menu-bar-mode 0)			; Turn off the menu bar (file, edit etc)
  (tool-bar-mode 0)			; Turn off the icons for new, save etc
  (blink-cursor-mode 0)			; Stop the cursor blinking
  (scroll-bar-mode 0)			; We don't need no scroll bar.
  (display-time-mode 1)			; Never have too many clocks.
#+end_src
**** Look and Feel 'Installed' Customisation.
*** Programming Customisation.
**** C/C++.
**** Python.
**** Clojure.
*** Text Editing.
**** HTML
**** LaTeX
**** Spell Checking
**** Grammar/Lint Checking
